--[[
    Vehicle Finder - the toggle bar icon.

    The icon is a 32x32 pixel-art car shipped with the mod
    (media/textures/VehicleFinder_Car.png, generated by tools/generate_icons.py).
    If the texture cannot be loaded for any reason the same car is drawn with
    plain rectangles instead, so the button is never a blank square.
]]

VehicleFinder = VehicleFinder or {}
local VF = VehicleFinder

local TEXTURE_PATHS = {
    "media/textures/VehicleFinder_Car.png",
    "media/textures/VehicleFinder_Car",
    "VehicleFinder_Car",
}

--- Cached lookup; getTexture is only ever called once.
function VF.getIcon()
    if VF._iconResolved then return VF._icon end
    VF._iconResolved = true
    for i = 1, #TEXTURE_PATHS do
        local ok, tex = pcall(getTexture, TEXTURE_PATHS[i])
        if ok and tex then
            VF._icon = tex
            break
        end
    end
    if not VF._icon then
        VF.warn("car texture not found, drawing the fallback icon")
    end
    return VF._icon
end

-- Fallback art, expressed on the same 32x32 grid as the png.
-- { x, y, w, h, r, g, b }
local FALLBACK = {
    { 2, 14, 29, 6, 0.55, 0.26, 0.21 },   -- body
    { 4, 13, 25, 1, 0.69, 0.36, 0.29 },   -- shoulder highlight
    { 8, 8, 14, 6, 0.09, 0.09, 0.10 },    -- cabin outline
    { 9, 9, 12, 4, 0.48, 0.58, 0.63 },    -- glass
    { 14, 9, 1, 4, 0.09, 0.09, 0.10 },    -- window divider
    { 2, 19, 29, 2, 0.36, 0.16, 0.14 },   -- sill
    { 5, 17, 7, 5, 0.09, 0.08, 0.10 },    -- rear wheel
    { 7, 19, 3, 2, 0.33, 0.33, 0.36 },    -- rear rim
    { 19, 17, 7, 5, 0.09, 0.08, 0.10 },   -- front wheel
    { 21, 19, 3, 2, 0.33, 0.33, 0.36 },   -- front rim
    { 29, 15, 2, 2, 0.87, 0.70, 0.32 },   -- head light
}

--- Draws the car on `panel` inside a size x size box at (x, y).
function VF.drawIcon(panel, x, y, size, alpha)
    local tex = VF.getIcon()
    if tex then
        panel:drawTextureScaled(tex, x, y, size, size, alpha, 1, 1, 1)
        return
    end
    local s = size / 32
    for i = 1, #FALLBACK do
        local p = FALLBACK[i]
        panel:drawRect(x + p[1] * s, y + p[2] * s, p[3] * s, p[4] * s,
                       alpha, p[5], p[6], p[7])
    end
end
